# GitHub Sponsor button / Botao Sponsor do GitHub
custom: "https://www.paypal.com/donate/?business=adrianojr59%40gmail.com&no_recurring=0&item_name=NX809J%20Kernel%20Driver%20Reconstruction&currency_code=USD"
