obj-m += zlog_test.o
zlog_test-y := zlog_test_main.o zlog_test_desc1.o zlog_test_desc2.o zlog_test_desc3.o zlog_test_desc4.o zlog_test_desc5.o zlog_test_state.o zlog_test_wq1.o zlog_test_work1.o zlog_test_wq2.o zlog_test_work2.o zlog_test_wq3.o zlog_test_work3.o zlog_test_wq4.o zlog_test_work4.o zlog_test_wq5.o zlog_test_work5.o
