/* Mechanically lifted from stock zte_power_supply_ocv2cap_simple@0x00101f10. */
.section .text,"ax",@progbits
.align 2
.globl zte_power_supply_ocv2cap_simple
.type zte_power_supply_ocv2cap_simple, %function
.word 0x29a87ac3
zte_power_supply_ocv2cap_simple:
  .inst 0x7100043f
  .inst 0x540002eb
  .inst 0x2a1f03e9
  .inst 0xaa0003e8
  .inst 0xb940010a
  .inst 0x6b02015f
  .inst 0x5400010b
  .inst 0x11000529
  .inst 0x91002108
  .inst 0x6b09003f
  .inst 0x54ffff41
  .inst 0x8b21cc08
  .inst 0xb85fc100
  .inst 0xd65f03c0
  .inst 0x34000149
  .inst 0x2940250a
  .inst 0x297f2d08
  .inst 0x4b0a004c
  .inst 0x4b09016b
  .inst 0x4b0a0108
  .inst 0x1b0b7d8b
  .inst 0x1ac80d68
  .inst 0x0b090100
  .inst 0xd65f03c0
  .inst 0xb9400400
  .inst 0xd65f03c0
.size zte_power_supply_ocv2cap_simple, .-zte_power_supply_ocv2cap_simple
