obj-m += gpio_keys_nubia.o
gpio_keys_nubia-y := gpio_keys_shutdown_exact.o gpio_keys_close_exact.o gpio_keys_open_exact.o gpio_keys_gpio_report_event_exact.o gpio_keys_gpio_work_func_exact.o gpio_keys_gpio_isr_exact.o gpio_keys_nubia_main.o
AFLAGS_gpio_keys_shutdown_exact.o := -g0 -I$(src)
AFLAGS_gpio_keys_close_exact.o := -g0 -I$(src)
AFLAGS_gpio_keys_open_exact.o := -g0 -I$(src)
AFLAGS_gpio_keys_gpio_report_event_exact.o := -g0 -I$(src)
AFLAGS_gpio_keys_gpio_work_func_exact.o := -g0 -I$(src)
AFLAGS_gpio_keys_gpio_isr_exact.o := -g0 -I$(src)
