.section .text,"ax",@progbits
.align 2
.global gf_parse_dts
.type gf_parse_dts, %function
.word 0xbcbc33b6
gf_parse_dts:
    .inst 0xd503233f
    .inst 0xa9bd7bfd
    .inst 0xa90157f6
    .inst 0xa9024ff4
    .inst 0x910003fd
    .inst 0xf9400c16
    .inst 0xaa0003f3
    .inst 0xf9417ed5
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, zte_goodix_pinctrl_init
    .inst 0x2a0003f4
    .inst 0x35000060
    .inst 0xf9404268
    .inst 0xb5000268
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_0982
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_0982
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03bb
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03bb
    .inst 0x2a1403e2
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03d3
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03d3
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03bb
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03bb
    .inst 0x2a1403e2
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0x2a1403e0
    .inst 0xa9424ff4
    .inst 0xa94157f6
    .inst 0xa8c37bfd
    .inst 0xd50323bf
    .inst 0xd65f03c0
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_01ee
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_01ee
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_06c3
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_06c3
    .inst 0x2a1f03e2
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0xf9404a61
    .inst 0xb40004c1
    .inst 0xb13ffc3f
    .inst 0x54000482
    .inst 0xf9404260
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, pinctrl_select_state
    .inst 0x34000140
    .inst 0xf9400e68
    .inst 0x2a0003f4
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_0a1e
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_0a1e
    .inst 0x90000002
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_1366
    .inst 0x91000042
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_1366
    .inst 0x91004100
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _dev_err
    .inst 0x37f80414
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_0205
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_0205
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03bb
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03bb
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0x5284e200
    .inst 0x5284ee81
    .inst 0x52800042
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, usleep_range_state
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_09a7
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_09a7
    .inst 0x910042c0
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, devm_regulator_get
    .inst 0xb13ffc1f
    .inst 0xf9004e60
    .inst 0x540002c3
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_02e4
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_02e4
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03bb
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03bb
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0xb9409a74
    .inst 0x17ffffc8
    .inst 0xf9400e68
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_0f84
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_0f84
    .inst 0x90000002
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_1366
    .inst 0x91000042
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_1366
    .inst 0x91004100
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _dev_err
    .inst 0x128002b4
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_02b6
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_02b6
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03bb
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03bb
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0x17ffffba
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, regulator_enable
    .inst 0x350001e0
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_109b
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_109b
    .inst 0xaa1503e0
    .inst 0x2a1f03e2
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, of_get_named_gpio
    .inst 0xb9004260
    .inst 0x36f802e0
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_1131
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_1131
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03bb
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03bb
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0x12800014
    .inst 0x14000040
    .inst 0x2a0003f4
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_0d91
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_0d91
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03bb
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03bb
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0xf9403e60
    .inst 0xb4fff440
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_1263
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_1263
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, zlog_client_record
    .inst 0xf9403e60
    .inst 0x52802041
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, zlog_client_notify
    .inst 0x17ffff9b
    .inst 0x2a0003e1
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_0a33
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_0a33
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0xb9404261
    .inst 0x90000002
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_045b
    .inst 0x91000042
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_045b
    .inst 0x910042c0
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, devm_gpio_request
    .inst 0x35000300
    .inst 0xb9404261
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_0a33
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_0a33
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_0e6b
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_0e6b
    .inst 0xaa1503e0
    .inst 0x2a1f03e2
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, of_get_named_gpio
    .inst 0xb9003e60
    .inst 0x36f803e0
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_077c
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_077c
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03bb
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03bb
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0x12800014
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_0d0b
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_0d0b
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03bb
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03bb
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0x14000010
    .inst 0x2a0003f4
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_08b8
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_08b8
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03bb
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03bb
    .inst 0x2a1403e2
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0xf9403e60
    .inst 0xb40000e0
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_0ac6
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_0ac6
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, zlog_client_record
    .inst 0xf9403e60
    .inst 0x52802021
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, zlog_client_notify
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_0f9f
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_0f9f
    .inst 0x17ffffab
    .inst 0x2a0003e1
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_0b75
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_0b75
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0xb9403e61
    .inst 0x90000002
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03c8
    .inst 0x91000042
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03c8
    .inst 0x910042c0
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, devm_gpio_request
    .inst 0x2a0003f4
    .inst 0x35000140
    .inst 0xb9403e60
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, gpio_to_desc
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, gpiod_direction_input
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_0a54
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_0a54
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03bb
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03bb
    .inst 0x2a1f03e2
    .inst 0x17ffff59
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_1375
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_1375
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_03bb
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_03bb
    .inst 0x2a1403e2
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0xf9403e60
    .inst 0xb4fff9a0
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, fp_goodix_exact_rodata_1200
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, fp_goodix_exact_rodata_1200
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, zlog_client_record
    .inst 0xf9403e60
    .inst 0x52802001
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, zlog_client_notify
    .inst 0x17ffffc6
.size gf_parse_dts, .-gf_parse_dts


