.section .text,"ax",@progbits
.align 2
.global syna_testing_check_dev_id_show
.type syna_testing_check_dev_id_show, %function
.inst 0x4e31a072
syna_testing_check_dev_id_show:
    .inst 0xd503233f
    .inst 0xd10403ff
    .inst 0xa90b7bfd
    .inst 0xf90063f9
    .inst 0xa90d5ff8
    .inst 0xa90e57f6
    .inst 0xa90f4ff4
    .inst 0x9102c3fd
    .inst 0xd5384108
    .inst 0xaa0203f3
    .inst 0xf9438908
    .inst 0xf81f83a8
    .inst 0xf9400c08
    .inst 0xa909ffff
    .inst 0xa908ffff
    .inst 0xa907ffff
    .inst 0xa906ffff
    .inst 0xa905ffff
    .inst 0xa904ffff
    .inst 0xa903ffff
    .inst 0xa902ffff
    .inst 0xf9400d08
    .inst 0xf9000bff
    .inst 0xf9404d17
    .inst 0x39560ae8
    .inst 0x36000ca8
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, syna_tcm_get_testing_0001
    .inst 0xb4000d20
    .inst 0x910063f8
    .inst 0x90000015
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_ad58
    .inst 0x910002b5
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_ad58
    .inst 0x90000016
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .bss+0x95e
    .inst 0x910002d6
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .bss+0x95e
    .inst 0xaa0003f4
    .inst 0x91004300
    .inst 0xaa1503e1
    .inst 0xaa1603e2
    .inst 0x390163ff
    .inst 0xa901ffff
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, __mutex_init
    .inst 0x91016300
    .inst 0xaa1503e1
    .inst 0xaa1603e2
    .inst 0xf9006e98
    .inst 0x91012319
    .inst 0x390283ff
    .inst 0xa9067fff
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, __mutex_init
    .inst 0x90000008
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_af58
    .inst 0x91000108
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_af58
    .inst 0xf9007299
    .inst 0xf90007e8
    .inst 0x52800088
    .inst 0xaa1403e1
    .inst 0xb90013e8
    .inst 0x910023e8
    .inst 0x2a1f03e2
    .inst 0xa903a29f
    .inst 0xf9400e88
    .inst 0xf94002e0
    .inst 0xb85fc110
    .inst 0x72895251
    .inst 0x72b03811
    .inst 0x6b11021f
    .inst 0x54000040
    .inst 0xd4304500
    .inst 0xd63f0100
    .inst 0x37f80aa0
    .inst 0x39404288
    .inst 0x90000009
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_7718
    .inst 0x91000129
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_7718
    .inst 0x7100011f
    .inst 0x90000008
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_87ff
    .inst 0x91000108
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_87ff
    .inst 0x9a891105
    .inst 0xf9400683
    .inst 0xb9400284
    .inst 0x90000002
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_1af3
    .inst 0x91000042
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_1af3
    .inst 0xaa1303e0
    .inst 0x52820001
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, scnprintf
    .inst 0xb94027e8
    .inst 0x2a0003f4
    .inst 0x34000168
    .inst 0xf9400fe8
    .inst 0x2a1403e9
    .inst 0x5282000a
    .inst 0xcb090141
    .inst 0x90000002
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_b524
    .inst 0x91000042
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_b524
    .inst 0xb9400103
    .inst 0x8b090260
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, scnprintf
    .inst 0x0b140014
    .inst 0xb9406fe8
    .inst 0x34000148
    .inst 0x2a1403e8
    .inst 0x52820009
    .inst 0xf94033e3
    .inst 0xcb080121
    .inst 0x90000002
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_7c88
    .inst 0x91000042
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_7c88
    .inst 0x8b080260
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, scnprintf
    .inst 0x0b140014
    .inst 0x394163e2
    .inst 0x350006c2
    .inst 0xf9400ff3
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, syna_request_managed_device
    .inst 0xb4000720
    .inst 0xb4000073
    .inst 0xaa1303e1
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, devm_kfree
    .inst 0x394283e2
    .inst 0xf90013ff
    .inst 0x390163ff
    .inst 0x35000702
    .inst 0xf94033f3
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, syna_request_managed_device
    .inst 0xb4000760
    .inst 0xb4000073
    .inst 0xaa1303e1
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, devm_kfree
    .inst 0x2a1403e0
    .inst 0x1400000e
    .inst 0x90000002
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_c246
    .inst 0x91000042
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_c246
    .inst 0xaa1303e0
    .inst 0x52820001
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, scnprintf
    .inst 0x14000007
    .inst 0x90000002
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_a791
    .inst 0x91000042
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_a791
    .inst 0xaa1303e0
    .inst 0x52820001
    .inst 0x52800023
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, scnprintf
    .inst 0x93407c00
    .inst 0xd5384108
    .inst 0xf9438908
    .inst 0xf85f83a9
    .inst 0xeb09011f
    .inst 0x54000541
    .inst 0xa94f4ff4
    .inst 0xf94063f9
    .inst 0xa94e57f6
    .inst 0xa94d5ff8
    .inst 0xa94b7bfd
    .inst 0x910403ff
    .inst 0xd50323bf
    .inst 0xd65f03c0
    .inst 0xf9400682
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_c281
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_c281
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_7c69
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_7c69
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0x90000005
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_7718
    .inst 0x910000a5
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_7718
    .inst 0x17ffffab
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_3313
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_3313
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_6a45
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_6a45
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0x17ffffc6
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_ad32
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_ad32
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_9fae
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_9fae
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0x17ffffc6
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_3313
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_3313
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_6a45
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_6a45
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0x17ffffc4
    .inst 0x90000000
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_ad32
    .inst 0x91000000
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_ad32
    .inst 0x90000001
    .reloc .-4, R_AARCH64_ADR_PREL_PG_HI21, .L_syna_testing_check_dev_id_show_rodata_9fae
    .inst 0x91000021
    .reloc .-4, R_AARCH64_ADD_ABS_LO12_NC, .L_syna_testing_check_dev_id_show_rodata_9fae
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, _printk
    .inst 0x17ffffc4
    .inst 0x94000000
    .reloc .-4, R_AARCH64_CALL26, __stack_chk_fail
.size syna_testing_check_dev_id_show, .-syna_testing_check_dev_id_show
.section .bss,"aw",@nobits
.org 0x960
.section .rodata.str1.1,"aMS",@progbits,1
.org 0x1af3
.L_syna_testing_check_dev_id_show_rodata_1af3:
.byte 0x0a, 0x25, 0x73, 0x20, 0x28, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x25, 0x64, 0x29, 0x3a, 0x20, 0x25, 0x73, 0x0a, 0x0a, 0x00
.org 0x3313
.L_syna_testing_check_dev_id_show_rodata_3313:
.byte 0x01, 0x33, 0x5b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5d, 0x20, 0x25, 0x73, 0x3a, 0x20, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x20, 0x73, 0x74, 0x69, 0x6c, 0x6c, 0x20, 0x69, 0x6e, 0x20, 0x75, 0x73, 0x65, 0x64, 0x2c, 0x20, 0x25, 0x64, 0x20, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x0a, 0x00
.org 0x6a45
.L_syna_testing_check_dev_id_show_rodata_6a45:
.byte 0x73, 0x79, 0x6e, 0x61, 0x5f, 0x74, 0x63, 0x6d, 0x5f, 0x62, 0x75, 0x66, 0x5f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x00
.org 0x7718
.L_syna_testing_check_dev_id_show_rodata_7718:
.byte 0x46, 0x61, 0x69, 0x6c, 0x00
.org 0x7c69
.L_syna_testing_check_dev_id_show_rodata_7c69:
.byte 0x73, 0x79, 0x6e, 0x61, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x64, 0x65, 0x76, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x00
.org 0x7c88
.L_syna_testing_check_dev_id_show_rodata_7c88:
.byte 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x20, 0x49, 0x44, 0x3a, 0x20, 0x25, 0x73, 0x0a, 0x00
.org 0x87ff
.L_syna_testing_check_dev_id_show_rodata_87ff:
.byte 0x50, 0x61, 0x73, 0x73, 0x00
.org 0x9fae
.L_syna_testing_check_dev_id_show_rodata_9fae:
.byte 0x73, 0x79, 0x6e, 0x61, 0x5f, 0x70, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x6d, 0x5f, 0x66, 0x72, 0x65, 0x65, 0x00
.org 0xa791
.L_syna_testing_check_dev_id_show_rodata_a791:
.byte 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x20, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x20, 0x69, 0x74, 0x65, 0x6d, 0x20, 0x69, 0x64, 0x3a, 0x25, 0x64, 0x0a, 0x00
.org 0xad32
.L_syna_testing_check_dev_id_show_rodata_ad32:
.byte 0x01, 0x33, 0x5b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5d, 0x20, 0x25, 0x73, 0x3a, 0x20, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x20, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x20, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x0a, 0x00
.org 0xad58
.L_syna_testing_check_dev_id_show_rodata_ad58:
.byte 0x28, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x20, 0x6d, 0x75, 0x74, 0x65, 0x78, 0x20, 0x2a, 0x29, 0x70, 0x74, 0x72, 0x00
.org 0xaf58
.L_syna_testing_check_dev_id_show_rodata_af58:
.byte 0x33, 0x39, 0x30, 0x38, 0x00
.org 0xb524
.L_syna_testing_check_dev_id_show_rodata_b524:
.byte 0x42, 0x75, 0x69, 0x6c, 0x64, 0x20, 0x49, 0x44, 0x3a, 0x20, 0x25, 0x64, 0x0a, 0x00
.org 0xc246
.L_syna_testing_check_dev_id_show_rodata_c246:
.byte 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x20, 0x69, 0x73, 0x20, 0x4e, 0x4f, 0x54, 0x20, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x0a, 0x00
.org 0xc281
.L_syna_testing_check_dev_id_show_rodata_c281:
.byte 0x01, 0x33, 0x5b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5d, 0x20, 0x25, 0x73, 0x3a, 0x20, 0x46, 0x61, 0x69, 0x6c, 0x20, 0x74, 0x6f, 0x20, 0x72, 0x75, 0x6e, 0x20, 0x74, 0x65, 0x73, 0x74, 0x2c, 0x20, 0x25, 0x73, 0x0a, 0x00
